version: "2.3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    image: simple-api
    container_name: skill-test
    ports:
      - "5050:5050"
# if you are using linux, please enable extra_hosts
#    extra_hosts:
#      - "host.docker.internal:172.17.0.1"