basePath: /auth
consumes:
- application/json
definitions:
  delivery.credential:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  delivery.successLogin:
    properties:
      token:
        example: eyWKEjdkcncEFMEDOmmdjfndckllfpvkfvnDKjdfmkrvmfg
        type: string
    type: object
  error_message.Duplicate:
    properties:
      message:
        example: the phone already exist
        type: string
    type: object
  error_message.Unauthorized:
    properties:
      message:
        example: unauthorized
        type: string
    type: object
  model.Fish:
    properties:
      area_kota:
        type: string
      area_provinsi:
        type: string
      komoditas:
        type: string
      price:
        type: string
      price_usd:
        type: string
      size:
        type: string
      tgl_parsed:
        type: string
      timestamp:
        type: string
      uuid:
        type: string
    type: object
  model.Summary:
    properties:
      area_provinsi:
        type: string
      avg:
        type: number
      max:
        type: integer
      median:
        type: number
      min:
        type: integer
    type: object
  model.User:
    properties:
      name:
        type: string
      phone:
        type: string
      role:
        type: string
    type: object
  model.UserResponse:
    properties:
      password:
        example: 1BtL
        type: string
    type: object
host: localhost:5050
info:
  contact: {}
  description: Documentation for Auth App and Fetch App
  title: Swagger Documentation APIs
paths:
  /app:
    get:
      description: fetch resources
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/model.Fish'
              type: array
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error_message.Unauthorized'
      summary: fetch
      tags:
      - fetch
  /auth/login:
    post:
      description: login user
      parameters:
      - description: request
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/delivery.credential'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/delivery.successLogin'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error_message.Unauthorized'
      summary: login
      tags:
      - auth
  /auth/register:
    post:
      description: register user
      parameters:
      - description: request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.UserResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/error_message.Duplicate'
      summary: register
      tags:
      - auth
  /auth/validate:
    get:
      description: validate
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error_message.Unauthorized'
      summary: validate
      tags:
      - auth
  /summary:
    get:
      description: summary resources
      parameters:
      - description: Bearer token
        in: header
        name: Authorization
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              items:
                $ref: '#/definitions/model.Summary'
              type: array
            type: array
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/error_message.Unauthorized'
      summary: fetch
      tags:
      - fetch
produces:
- application/json
swagger: "2.0"
